//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace formChat.referenciaChat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="referenciaChat.chatSoap")]
    public interface chatSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mensaje del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Chatear", ReplyAction="*")]
        formChat.referenciaChat.ChatearResponse Chatear(formChat.referenciaChat.ChatearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Chatear", ReplyAction="*")]
        System.Threading.Tasks.Task<formChat.referenciaChat.ChatearResponse> ChatearAsync(formChat.referenciaChat.ChatearRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChatearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Chatear", Namespace="http://tempuri.org/", Order=0)]
        public formChat.referenciaChat.ChatearRequestBody Body;
        
        public ChatearRequest() {
        }
        
        public ChatearRequest(formChat.referenciaChat.ChatearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChatearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mensaje;
        
        public ChatearRequestBody() {
        }
        
        public ChatearRequestBody(string mensaje) {
            this.mensaje = mensaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChatearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChatearResponse", Namespace="http://tempuri.org/", Order=0)]
        public formChat.referenciaChat.ChatearResponseBody Body;
        
        public ChatearResponse() {
        }
        
        public ChatearResponse(formChat.referenciaChat.ChatearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChatearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChatearResult;
        
        public ChatearResponseBody() {
        }
        
        public ChatearResponseBody(string ChatearResult) {
            this.ChatearResult = ChatearResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface chatSoapChannel : formChat.referenciaChat.chatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class chatSoapClient : System.ServiceModel.ClientBase<formChat.referenciaChat.chatSoap>, formChat.referenciaChat.chatSoap {
        
        public chatSoapClient() {
        }
        
        public chatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public chatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public chatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public chatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        formChat.referenciaChat.ChatearResponse formChat.referenciaChat.chatSoap.Chatear(formChat.referenciaChat.ChatearRequest request) {
            return base.Channel.Chatear(request);
        }
        
        public string Chatear(string mensaje) {
            formChat.referenciaChat.ChatearRequest inValue = new formChat.referenciaChat.ChatearRequest();
            inValue.Body = new formChat.referenciaChat.ChatearRequestBody();
            inValue.Body.mensaje = mensaje;
            formChat.referenciaChat.ChatearResponse retVal = ((formChat.referenciaChat.chatSoap)(this)).Chatear(inValue);
            return retVal.Body.ChatearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<formChat.referenciaChat.ChatearResponse> formChat.referenciaChat.chatSoap.ChatearAsync(formChat.referenciaChat.ChatearRequest request) {
            return base.Channel.ChatearAsync(request);
        }
        
        public System.Threading.Tasks.Task<formChat.referenciaChat.ChatearResponse> ChatearAsync(string mensaje) {
            formChat.referenciaChat.ChatearRequest inValue = new formChat.referenciaChat.ChatearRequest();
            inValue.Body = new formChat.referenciaChat.ChatearRequestBody();
            inValue.Body.mensaje = mensaje;
            return ((formChat.referenciaChat.chatSoap)(this)).ChatearAsync(inValue);
        }
    }
}
